### ISSUE TITLE
Add Simplified Chinese translation for the memories.mdx .

### ISSUE THREAD

**Issue by Dreaminko** [vertesan/hatsuboshi-library#18]
[memories_zh-Hans.zip](https://github.com/user-attachments/files/17276815/memories_zh-Hans.zip)

**Comment by vertesan** [comment]
Hi, thanks for translating `memories.mdx`.

Since manually transferring code files to each other in developing is not supposed to be a good practice ~~(why do we use git)~~, could you add a file named `memories_zh-Hans.mdx` under the same directory as `memories.mdx` and submit your PR please? That way git will record your contribution for the file. 

Once the translation file is ready I can take care of other follow up works for you.

**Comment by vertesan** [comment]
Close as completed
